<h3>Here are all the exercises from exercise set 1.<h3>

<h3>Exercise 1.1<h3>

In [4]:
# Create a list to store 15 number ones 
ones = []

# Create for loop to append 15 number ones to the previously created list(ones) above
for x in range(15):
    ones.append(1)

# Create print to display the list of ones to the user
print(f"Here is 15 ones: {ones}")

# Create list to store 15 number sevens
sevens = []

# Create for loop to append 15 number sevens to the previously created list(sevens) above
for x in range(15):
    sevens.append(7)

# Create a print to display the 15 number sevens to the user
print(f"Here is 15 sevens: {sevens}")

# Create list to store numbers between 100-150
list100_150 = []

# Create for loop to append x to the previously created list, +1 to the x to create list(list100_150) of numbers between 100-150, +1 to 151 to get all,
# numbers between 100-150"
for x in range(100, 151):
    list100_150.append(x)
    x += 1

# Create print to display numbers between 100-150 to the user
print(f"Here is list of numbers between 100-150: {list100_150}")

# Create list to store even numbers between numbers 0-100
even_numbers = []

# Create for loop to calculate even numbers between 0-100, use if loop to append information to the privously created list
for x in range(0, 102):
    evens = x%2
    if evens == 0:
        even_numbers.append(x)

# Create print to display the list(even_numbers) of even numbers between 0-100 to the user
print(f"Here is list of even numbers between numbers 0-100: {even_numbers}")

# Create a list to store years divisable by 4
divisable_years = []

# Create for loop to calculate years divisable by 4 between years 1950-2020
for x in range(1950, 2024):
    years_divided = x%4
    if years_divided == 0:
        divisable_years.append(x)

# Create print to display the list(divisable_years) of years divisable by 4
print(f"Here are all the years divisable by number 4 between years 1950-2020: {divisable_years}")

Here is 15 ones: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Here is 15 sevens: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]
Here is list of numbers between 100-150: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]
Here is list of even numbers between numbers 0-100: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
Here are all the years divisable by number 4 between years 1950-2020: [1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


<h3>Under this markdown you can find all code imports to display all the following exercises!<h3>

In [5]:
# Import numpy as np, so it can be used in the following exercises
import numpy as np

In [6]:
%load_ext numpy_html

The numpy_html extension is already loaded. To reload it, use:
  %reload_ext numpy_html


In [7]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h2>Exercise 1.2<h2>


<h2>Following exercises have been created with the help of numpy.<h2>

In [8]:
# Create an array of 15 number 0
zeros = np.zeros((1, 15)).astype(int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
# Create an array of 15 number 1
ones = np.ones((1, 15)).astype(int)
ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
# Create an array of 15 number 7
sevens = np.zeros((1, 15)).astype(int) + 7
sevens

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [11]:
# Create an array of numbers between 100-150, +1 to 150 to get all numbers between the numbers
num100_150 = np.arange(100, 151)
num100_150

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [12]:
# Create an array of between numbers 1900-2021, +1 to the 2021 to get all numbers between numbers 1900-2021
num1900_2020 = np.arange(1900, 2022)
num1900_2020

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [13]:
# Create an array of even numbers between 0-100 with the help of numpy
num0_100_numpy = np.arange(0, 102, 2)
num0_100_numpy

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
# Create an array of years divisable by 4 between years 1950-2020
numpy_divi_years = np.arange(1950, 2022, 4)
numpy_divi_years

array([1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978, 1982, 1986, 1990,
       1994, 1998, 2002, 2006, 2010, 2014, 2018])

<h2>Exercise 1.3<h2>

In [15]:
# Create a vector list of numbers(5, 16, 9, 2, 19, 18, 7)
vector_list = ([5, 16, 9, 2, 19, 18, 11, 7])

# Create a sentence, which finds max position of largest value in the vector
vect_listmax = np.argmax(vector_list)
vect_listmax

4

In [16]:
# Create 7x7 matrix of values between 1-49
value_array = np.arange(1,50)
matrix_7x7 = value_array.reshape(7,7)
matrix_7x7

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [17]:
# Create a 8x8 matrix of random numbers
rand_values = np.random.randint(0, 5, 64).reshape(8, 8)
matrix_8x8 = rand_values.reshape(8, 8)
matrix_8x8

array([[3, 4, 1, 2, 1, 1, 0, 1],
       [2, 4, 4, 3, 4, 3, 2, 2],
       [4, 3, 0, 3, 3, 2, 3, 0],
       [4, 2, 0, 2, 3, 2, 4, 1],
       [2, 1, 3, 4, 2, 1, 1, 1],
       [4, 0, 1, 4, 1, 4, 4, 1],
       [1, 2, 2, 1, 1, 2, 1, 1],
       [1, 4, 3, 0, 1, 0, 2, 0]])

In [18]:
# Create 8x8 matrix of random numbers by using standard normal distributions(values between -3 and 3)
random_values = np.random.randint(-3, 3, 64)
random_matrix_8x8 = random_values.reshape(8, 8)
random_matrix_8x8

array([[-2, -3,  0, -3,  2,  0, -3, -3],
       [-3,  1, -2, -2,  2,  1, -1, -1],
       [ 2,  2, -3, -3,  0, -3, -3,  2],
       [ 1,  2,  1,  0, -1,  1,  1, -3],
       [-1,  2,  2,  0, -3, -1,  1,  2],
       [-2, -3, -3, -2,  0, -3,  0, -2],
       [ 1,  2,  1, -1, -1,  0, -1, -3],
       [-2, -3,  1,  0, -1, -1, -2,  1]])

<h2>Exercise 1.4<h2>

In [19]:
# Create array of 10 values between 0 and 1 with the help of linspace
zero_to_one = np.linspace(0, 1, 10)
zero_to_one_matrix = zero_to_one.reshape(2, 5)
zero_to_one_matrix

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444],
       [0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]])

In [20]:
# Create a 10x10 matrix of all values between 0 and 5 by using linspace
one_to_five = np.linspace(0, 5, 100)
one_to_five_matrix = one_to_five.reshape(10, 10)
one_to_five_matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

<h2>Exercise 1.5<h2>

In [21]:
# Create a 3x5 matrix from values(23, 34, 54, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51)
matrix1_5a = np.array([23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51]).reshape(3, 5)
matrix1_5a

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [22]:
# Create a 8x16 matrix from values between  128-256
matrix1_5b = np.arange(128, 256).reshape(8, 16)
matrix1_5b

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [23]:
# Create 10x10 matrix from values between 0 and 5 with 0.05 increase to previous value
matrix1_5c= np.arange(0, 5, 0.05).reshape(10, 10)
matrix1_5c


array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45],
       [0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95],
       [1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45],
       [1.5 , 1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95],
       [2.  , 2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45],
       [2.5 , 2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95],
       [3.  , 3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45],
       [3.5 , 3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95],
       [4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45],
       [4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95]])

<h2>Exercise 1.6<h2>

In [24]:
# Create 6x6 matrix called dataset from numbers between 1-36
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [25]:
# Create a function to get values(21-36) from the data set, column 4 row 3 to column 6 row 6
matrix_1 = dataset[3:6, 2:6]
matrix_1

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [26]:
# Create a function to get values(4, 10, 16 and 22) from the dataset, column 1 row 4 to column 4 row 4
matrix_2 = dataset[0:4, 3]
matrix_2

array([ 4, 10, 16, 22])

In [27]:
# Create a function to get values from 3rd column
matrix_3 = dataset[2]
matrix_3

array([13, 14, 15, 16, 17, 18])

In [28]:
# Get values from 4th to 7th row
matrix_4 = dataset[3:6]
matrix_4

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h2>Exercise 1.7<h2>

In [29]:
# Create a 7x7 matrix of numbers between 1-50 
dataset_values = np.arange(1, 50).reshape(7, 7)
dataset_values

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [30]:
# Add + 70 to all numbers in the previously created matrix
dataset = np.arange(1, 50).reshape(7, 7) + 70
dataset

array([[ 71,  72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118, 119]])

In [31]:
# Create sentence to get sum of all numbers in the matrix
dataset_total1 = np.sum(dataset_values)
dataset_total1

1225

In [32]:
# Create a function to get total of odd values in the dataset
odd_values = np.arange(1, 50, 2)
odd_values_total = np.sum(odd_values)
odd_values_total



625

In [33]:
# Create a function to get standard deviation of dataset_values
dataset_deviation = np.std(dataset_values)
dataset_deviation

14.142135623730951

In [34]:
# Create a function to get sum by a row
dataset_matrix = np.arange(1, 50).reshape(7, 7)
dataset_3total = np.sum(dataset_matrix, axis=1)
dataset_3total

array([ 28,  77, 126, 175, 224, 273, 322])

In [35]:
# Create a function to get sum by a column
dataset_4total = np.sum(dataset_matrix, axis=0)
dataset_4total

array([154, 161, 168, 175, 182, 189, 196])

<h2>Here are all extra exercises from exercise set 1.<h2>

<h3>1.3b extra<h3>

In [38]:
# Create a list to store values of the matrix
matrix = []

# Create starting value to be used in creating the variables
start_value = 1

# Create a statement to define values of rows in the matrix
for x in range(7):
    row = []
    # Create statement to add +1 to starting value and add starting value into row
    for x in range(7):
        row.append(start_value)
        start_value += 1
    # Add row into the matrix
    matrix.append(row)

# Create statement to display matrix
for row in matrix:
    print(row)


[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


<h3>1.4b extra<h3>

In [37]:
# Create a function to calculate linearly spaced list
def linspace(start, stop, num):
    # Calculate the step size
    values = (stop - start) / (num - 1)
    values_list = []
    # Generate linearly spaced values and append them to the result list
    for i in range(num):
        values_list.append(start + values * i)
    return values_list

# Generate linearly spaced list between 0 and 5 with 100 values
matrix_05values = linspace(0, 5, 100)

# Create a list to store the 10x10 matrix
matrix_05 = []
# Create statement to create rows into the matrix list, there are 10 rows, which each hold 10 values
for i in range(0, 100, 10):
    # Slice the list into 10 rows and add them to the matrix list
    row = matrix_05values[i:i+10]
    matrix_05.append(row)

# Create statement to display the result to the user
for row in matrix_05:
    print(row)


[0.0, 0.050505050505050504, 0.10101010101010101, 0.15151515151515152, 0.20202020202020202, 0.25252525252525254, 0.30303030303030304, 0.35353535353535354, 0.40404040404040403, 0.45454545454545453]
[0.5050505050505051, 0.5555555555555556, 0.6060606060606061, 0.6565656565656566, 0.7070707070707071, 0.7575757575757576, 0.8080808080808081, 0.8585858585858586, 0.9090909090909091, 0.9595959595959596]
[1.0101010101010102, 1.0606060606060606, 1.1111111111111112, 1.1616161616161615, 1.2121212121212122, 1.2626262626262625, 1.3131313131313131, 1.3636363636363635, 1.4141414141414141, 1.4646464646464645]
[1.5151515151515151, 1.5656565656565655, 1.6161616161616161, 1.6666666666666667, 1.7171717171717171, 1.7676767676767677, 1.8181818181818181, 1.8686868686868687, 1.9191919191919191, 1.9696969696969697]
[2.0202020202020203, 2.0707070707070705, 2.121212121212121, 2.1717171717171717, 2.2222222222222223, 2.2727272727272725, 2.323232323232323, 2.3737373737373737, 2.4242424242424243, 2.474747474747475]
[2.